import type { Metadata } from "next";

import { Separator } from "@/components/ui/separator";
import { Header } from "./_/components/Header";
import { Providers } from "./_/providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <div className="md:container md:mx-auto p-4 sm:px-6 lg:px-8">
          <Providers>
            <Header />
            <Separator className="mb-4" />
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
