import type { Metadata } from "next";

import { Providers } from "./_/providers";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <div className="md:container md:mx-auto p-4 sm:px-6 lg:px-8">
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
